### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by SLiX69** [WolfgangFahl/pdfindexer#7]
Hi,

nice project, runs very well, but I have problems with special characters, more precisely with the special characters ä, ö, ü, etc. Words, which contain these, are not indexed (-> 0 count in html).
My keyWordFile is encoded in UTF-8. With SumatraPDF or other PDF readers the search function does work with special chars.

Am I missing something or are special characters not supported?

regards

**Comment by WolfgangFahl** [comment]
Thank you for reporting the issue.
Although i am german and need Umlauts in my usecase in principle we didn't run into the issue since the keywords we use seem to have no umlauts so i don't have an example myself where the problem occurs. Could you please supply a small PDF example showing the issue. The goal is to have a JUnit testcase that fails on such an example. So it would be great if you could create a pull-request containing the example + the JUnit test. In any case I'll happily look into this and help fixing or finding a work around. I do not see any reason why the underlying Apache library should not support UTF-8 characters.

**Comment by SLiX69** [comment]
I modified the test cases and there are no problems at all.
The problems occured while using the .jar file, from command line.

Thanks for your input, I'm writing a short main which does what I need so I don't need to use the jar file.
My problem is solved, feel free to close the issue, if you feel like it!

**Comment by WolfgangFahl** [comment]
I see - so it might be the platform default encoding is different. The fix for that is described in https://stackoverflow.com/a/10890594/1497139.  With adding http://wiki.bitplan.com/index.php/PdfIndexer#Character_set_handling I am closing this ticket.
